#!/usr/bin/env bash
set -euo pipefail

BRANCH="${1:-feat/chatgpt-change}"
PR_TITLE="${2:-"Apply ChatGPT patch"}"
PR_BODY_FILE="$(mktemp)"

git rev-parse --is-inside-work-tree >/dev/null 2>&1 || { echo "Not a git repo"; exit 1; }
command -v gh >/dev/null 2>&1 || { echo "gh CLI required"; exit 1; }

PATCH_FILE="$(mktemp)"
cat > "$PATCH_FILE"

git checkout -b "$BRANCH"
git apply --whitespace=fix "$PATCH_FILE"
git add -A
git commit -m "$PR_TITLE"
git push -u origin "$BRANCH"

echo -e "$PR_TITLE\n\nPatch generated by ChatGPT." > "$PR_BODY_FILE"
gh pr create --title "$PR_TITLE" --body "$PR_BODY_FILE" --fill || {
  echo "Could not open PR automatically. Open on GitHub."
}
echo "✅ Done. Branch: $BRANCH"
