name: CI
on:
  pull_request:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff mypy pytest
      - name: Ruff (lint & format check)
        run: |
          ruff check .
          ruff format --check .
      - name: Mypy (types)
        run: mypy .
      - name: Pytest
        run: pytest -q
